### ISSUE TITLE
how to install it on my TV

### ISSUE THREAD

**Issue by simplephp** [IssamElNass/React-Samsung-Smart-Tv-Template#1]
Hey bro~ I want now how to install and run my smart tv? how to pack it? thx @^_^

**Comment by IssamElNass** [comment]
Hey! 

After following the [Wiki](https://github.com/IssamElNass/React-Samsung-Smart-Tv-Template/wiki) you must build your react project and copy the dist folder to the folder where you made your tizen studio project. 

Hope you'll understand!

**Comment by awdeveloper00** [comment]
Hello, I am having problem with focusing on the initial element of the next row. The props that are giving for Focusable Section dont seem to work ?, Any help from you would really be appreciated. Thank you.
